### ISSUE TITLE
setLibraryList and sql user defined functions

### ISSUE THREAD

**Issue by beckhamrryyaann** [IBM/nodejs-idb-pconnector#104]
It appears when trying to call a user defined function in sql, it is not using my library list for my connection that I have setup.  
"Select getUserData() as data from sysdummy1".  This statement does not work as it is saying it can't find the function.  If I qualify as testlib.getUserData() it will work.
Thank  you.

**Comment by abmusse** [comment]
Yes you will need to set your library list. Take a look at this example https://github.com/IBM/nodejs-idb-pconnector#setlibrarylist

**Comment by beckhamrryyaann** [comment]
Yes.. I did that.  It works well when using  on database files in the From
part of my sql....
But when trying to use an UDF in my select part, it is still making me
qualify the library.  Is this intentional?

Ryan

**Comment by kadler** [comment]
Library list is only used when running in system naming mode. The default is SQL naming, which doesn't use the library list. @abmusse is there a way to switch to system naming with idb-pconnector?
