### ISSUE TITLE
Calling Store Proc passing well IN parms , not getting OUT parm

### ISSUE THREAD

**Issue by jsanguin** [IBM/nodejs-idb-pconnector#124]
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 53
ETag: W/"35-dpDjXKZ3Z4G5gqI/bkEEgYghBkc"
Date: Sat, 06 Aug 2022 01:01:49 GMT
Connection: close

First name: Pedro, last name: Sifuentes, full name:  

**Describe the bug**
The output parameter is not being passed to the Node.js variable fullName. I can see my store proc passing that value back (actually I tested from a RPGLE with SQL and saw the result) . Don't know why this result does not reach my variable in Node.js.

**To Reproduce**
1. Just doing.. POST  http://fx7:5000/test/fullname?first=Pedro&last=Sifuentes

2. 
3. 
4. 

**Expected behavior**
Full name should have first name + last name

**Screenshots**

**Additional context**

**Comment by kadler** [comment]
Please provide a description of the RPG stored procedure along with node-odbc code to recreate the problem. Posting a link to an internal web app is not helpful to us.

**Comment by jsanguin** [comment]
I would like to close this, please read issue #126 which explains the findings. Thanks.
