### ISSUE TITLE
DBPool creates 16 connections when incrementsSize = 10

### ISSUE THREAD

**Issue by oneworks** [IBM/nodejs-idb-pconnector#27]
const pool = new DBPool({ url: "*LOCAL" }, { debug: true , incrementSize: 10});

The above statement creates 16 connections.  Is this expected?

The following shows in the log file.

Creating Connection 0...
Connection 0 created    
Creating Connection 1...
Connection 1 created    
Creating Connection 2...
Connection 2 created    
Creating Connection 3...
Connection 3 created    
Creating Connection 4...
Connection 4 created    
Creating Connection 5...
Connection 5 created    
Creating Connection 6...
Connection 6 created    
Connection 7 created    
Creating Connection 8...
Connection 8 created    
Creating Connection 9...
Connection 9 created    
Creating Connection 0...
Connection 0 created    
Creating Connection 1...
Connection 1 created    
Creating Connection 2...
Connection 2 created    
Creating Connection 3...
Connection 3 created    
Creating Connection 4...
Connection 4 created    
Creating Connection 5...
Connection 5 created    
Creating Connection 6...
Connection 6 created    
Creating Connection 7...
Connection 7 created

**Comment by kadler** [comment]
Obviously it counts in hex :joy:

**Comment by abmusse** [comment]
> The above statement creates 16 connections. Is this expected?
@oneworks That is not expected, it should create 10 connections.

I tried to recreate the issue with:

```javascript
const {DBPool} = require('idb-pconnector');

const pool = new DBPool({ url: "*LOCAL" }, { debug: true , incrementSize: 10});

console.log(`Pool contains: ${pool.connections.length} connections`);

```

my output was

```
Creating Connection 0...
Connection 0 created
Creating Connection 1...
Connection 1 created
Creating Connection 2...
Connection 2 created
Creating Connection 3...
Connection 3 created
Creating Connection 4...
Connection 4 created
Creating Connection 5...
Connection 5 created
Creating Connection 6...
Connection 6 created
Creating Connection 7...
Connection 7 created
Creating Connection 8...
Connection 8 created
Creating Connection 9...
Connection 9 created
Pool contains: 10 connections

```

I'm only seeing 10 connections created.

Are you redirecting `stdout` to a log file?

When you have debug set to true then Creating connection output is printed at startup each time.

**Comment by oneworks** [comment]
The job is submitted with the following environment variable


ADDENVVAR ENVVAR(QIBM_QSH_CMD_OUTPUT) VALUE(‘FILEAPPEND=node _log.txt’)



This is where I’m seeing the extra connections

**Comment by oneworks** [comment]
You got me thinking….

I’ve created a helper script called db_promise.js

const { DBPool } = require("idb-pconnector");
const pool = new DBPool({ url: "*LOCAL" }, { debug: true , incrementSize: 10});

var pdb = {};

pdb.query = async function(sql) {
  /*
   * Directly execute a statement by providing the SQL to the runSql() function.
   * NOTE: Stored Procedures must use the prepareExecute() method instead.
   */
  try {
    return await pool.runSql(sql);
  } catch (error) {
    throw Error(error);
  }
};

module.exports = pdb;


Then in my express scripts I import it in.  Turns out I had the DBPool here too.  So, that was the issue.  Apologies.
Once I removed it, the log was correct.
On a side note, is having an external DB helper script the optimal way to handle it?

const express = require("express");
const app = express();
const router = express.Router();
const pdb = require("./db_promise");
const { DBPool } = require("idb-pconnector");
const pool = new DBPool({ url: "*LOCAL" }, { debug: true });

const dataLib = process.env.DATALIB;
const commonLib = process.env.COMMONDATALIB;
const surroundLib = process.env.SURROUNDDATALIB;
const pgmLib = process.env.PROGRAMLIB;

// Define routes

// Get part lines from UDC 41/S1
router.post("/api/part/list/", function(req, res, next) {
  (async () => {
    try {
      let sql =
        "select trim(cast(drky as char(10) ccsid 37)) as LineId," +
        "drdl01 as LineDescription from " +
        commonLib +
        ".f0005 " +
        "WHERE DRSY = '41' and DRRT = 'S1' and DRDL02 <> ' ' order by drky";

      let rs = await pdb.query(sql);
      if (rs.length > 0) {
        let prefix = '{ "Response":{ "Line":';
        let newRS =
          prefix +
          JSON.stringify(rs) +
          ', "correlationID":"' +
          req.body.Header.correlationID +
          '","Tracking": { "isSuccess": "true" }}}';
        res.writeHead(200, { "Content-Type": "application/json" });
        res.status(200).end(newRS);
      } else {
        let rs =
          '{"Response": { "Line":' +
          "{" +
          '"correlationID":"' +
          req.body.Header.correlationID +
          '",' +
          '"Tracking":{' +
          '"isSuccess":"false",' +
          '"Fault":{' +
          '"code":"SF001",' +
          '"message":"No records found matching search criteria",' +
          '"stacktrace":""}}}}}';
        res.writeHead(200, { "Content-Type": "application/json" });
        res.status(200).end(rs);
      }
    } catch (err) {
      let rs =
        '{"Response": { "Line":' +
        "{" +
        '"correlationID":"' +
        req.body.Header.correlationID +
        '",' +
        '"Tracking":{' +
        '"isSuccess":"false",' +
        '"Fault":{' +
        '"code":"SF000",' +
        '"message":"' +
        err +
        '",' +
        '"stacktrace":""}}}}}';
      res.writeHead(400, { "Content-Type": "application/json" });
      res.status(400).end(rs);
      var d = new Date();
      console.log("Query error: " + d.toLocaleString() + " " + err);
    }
  })();
});




Steve Hildebrand
OneWorks Business Solutions, Inc.
shildebrand@oneworksinc.com
828-493-0096

**Comment by abmusse** [comment]
@oneworks 

In this case why not just use `DBPool.runSql()` directly within the post route?

I think that would be more efficient and simpler than wrapping with the helper script.

**Comment by abmusse** [comment]
FYI, DBPool provides a prepare, bind, and execute helper: [DBPool.prepareExecute()](https://github.com/IBM/nodejs-idb-pconnector#prepareexecute).

I would highly recommend using helper functions provided: 
- `DBPool.runSql()` 
- `DBPool.prepareExecute()` 

directly instead of recreating that functionality

If you wanted to stick to using `db_promise.js` helper script I would only require `DBPool` within that file.

So that you avoid creating unused connections.

**Comment by oneworks** [comment]
I’ll do that.

Thanks for the help!

**Comment by oneworks** [comment]
I started thinking on this again…

If I have, say 10 separate express route scripts, and each one had the following, wouldn’t each script create 10 connections?

const { DBPool } = require("idb-pconnector");
const pool = new DBPool({ url: "*LOCAL" }, { debug: true, incrementSize: 10 });


Also, is there a way for idb-pconnector to return the variables as mixed case, as specified in the SQL?  Currently, everything returns as all CAPS.
