### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by kadler** [IBM/nodejs-idb-pconnector#3]
We should copy over contribution guidelines from https://github.com/IBM/repo-template

In addition, we can set up the DCO bot to ensure non-Collaborators have signed off on the DCO.

**Comment by abmusse** [comment]
PR https://github.com/IBM/nodejs-idb-pconnector/pull/29 adds the file.

Next step setup the bot.

**Comment by abmusse** [comment]
DCO bot is now setup also
