### ISSUE TITLE
connection.setConnAttr fails

### ISSUE THREAD

**Issue by lae0901** [IBM/nodejs-idb-pconnector#35]
would like to switch the connection to system naming mode and set the library list. How to do that?

when I run connection.setConnAttr( 3017, 1 ) the statement fails with error code 9 - argument value not valid. 
3017 is the constant for SQL_ATTR_DBC_SYS_NAMING.  and 1 is the constant for SQL_TRUE..

```
const { Connection } = require('idb-pconnector');
async function execExample()
{
  try
  {
    const connection = new Connection({ url: '*LOCAL' });

    // constants from here: https://github.com/php/pecl-database-ibm_db2/blob/master/php_ibm_db2.h
    const sql_sys_naming = 3017; // #define SQL_ATTR_DBC_SYS_NAMING 3017
    const sql_true = 1;
    const sql_false = 0;

    // trying to set the connection to system naming mode.
    await connection.setConnAttr(sql_sys_naming, sql_true);

  } catch (error)
  {
    console.error(`Error was: \n${error.stack}`);
  }
}

execExample();

````

running the code from QP2TERM:

node steve7d.js                                                                                    
Error was:                                                                                         
Error: SQLSTATE=HY009 SQLCODE=-99999 Error occurred in SQL Call Level Interface                    
    at Promise (/home/njs/node_modules/idb-pconnector/lib/idb-pconnector.js:135:24)                
    at new Promise (<anonymous>)                                                                   
    at Connection.setConnAttr (/home/njs/node_modules/idb-pconnector/lib/idb-pconnector.js:133:12) 
    at execExample (/home/njs/steve7d.js:19:22)                                                    
    at Object.<anonymous> (/home/njs/steve7d.js:27:1)                                              
    at Module._compile (module.js:653:30)                                                          
    at Object.Module._extensions..js (module.js:664:10)                                            
    at Module.load (module.js:566:32)                                                              
    at tryModuleLoad (module.js:506:12)                                                            
    at Function.Module._load (module.js:498:3)                                                     
$                                                                                                  

30   02/25/19  05:24:26.174043  QSQCLI       QSYS        *STMT    QP2USER2    QSYS   
  From module . . . . . . . . :   SQLSCA                                             
  From procedure  . . . . . . :   SQLSetConnectAttr                                  
  Statement . . . . . . . . . :   17088                                              
  To module . . . . . . . . . :   QP2API                                             
  To procedure  . . . . . . . :   runpase_common__FiPvT2                             
  Statement . . . . . . . . . :   4                                                  
  Message . . . . :   Error occurred in SQL Call Level Interface                     
  Cause . . . . . :   A procedure call encountered an error.  The error code is      
    9. Error codes are: 1 -- Memory allocation failure. 2 -- Column number not       
    valid. 3 -- Program type out of range. 4 -- SQL data type out of range. 8 --     
    Operation canceled. 9 -- Argument value not valid. 10 -- Function sequence       
    error. 12 -- Transaction operation state not valid. 13 -- Memory management      
    problem. 14 -- Maximum number of handles allocated. 15 -- No cursor name

**Comment by abmusse** [comment]
Hi @lae0901

This package uses constants provided from [idb-connector](https://github.com/IBM/nodejs-idb-connector/blob/master/lib/db2a.js#L625)  within that package looks like the value of `SQL_ATTR_DBC_SYS_NAMING `is equal to  10004.

You can gain access to the available constants from the requiring `idb-pconnector`:

```
const { Connection, SQL_ATTR_DBC_SYS_NAMING, SQL_TRUE } = require('idb-pconnector');

const connection = new Connection({ url: '*LOCAL' });

await connection.setConnAttr(SQL_ATTR_DBC_SYS_NAMING, SQL_TRUE);
```

**Comment by lae0901** [comment]
thanks Abdirahim.   this works.

to set the library list I have to call an SQL procedure thru the Connection and run the CHGLIBL command?

I tried to run "set current path = myLib1, myLib2" and it had no affect.  Maybe because I have switched to system naming mode?
```
    {
      const stmt = new Statement(connection);
      const sql = 'set current_path = couri7, aplusb1fcc';
      const rv1 = await stmt.prepare(sql);
      await stmt.execute();
    }

```

Would be ideal to specify the library list when the code opens the connection.  That is how it works in PHP.

-Steve

**Comment by abmusse** [comment]
Yes you would need to call CHGLIBL command through QCMDEXC stored procedure as mentioned [here](https://github.com/IBM/nodejs-idb-connector/issues/30#issuecomment-457334933)

I am considering adding a function `connection.setLibraryList()`

That would call QCMDEXC under the covers

**Comment by abmusse** [comment]
Hi Steve, did a call to `QSYS2.QCMDEXC` solve the issue?
