### ISSUE TITLE
Cannot pass null as part of parameter array to prepareExecute()

### ISSUE THREAD

**Issue by KerimG** [IBM/nodejs-idb-pconnector#40]
Version 1.0.4

When trying to pass following params array to prepareExecute()

```js
[ 'Nicholas Runolfsdottir V',
  'Maxime_Nienow',
  'Sherwood@rosamond.me',
  'Ellsworth Summit',
  'Suite 729',
  'Aliyaview',
  '45169',
  { value: null },
  { value: null },
  '586.493.6943 x140',
  { value: null } ]
```

one gets the following error: 

```
Error: The parameter object must define a value property
    at params.forEach (/home/GUENEY/code/obi/node_modules/idb-pconnector/lib/dbPool.js:332:17)
    at Array.forEach (<anonymous>)
    at DBPool.setupParams (/home/GUENEY/code/obi/node_modules/idb-pconnector/lib/dbPool.js:327:12)
    at DBPool.prepareExecute (/home/GUENEY/code/obi/node_modules/idb-pconnector/lib/dbPool.js:260:38)
```

The problem lies in the dbPool.js' setupParams function:

```js
if (!value) {
    throw new Error('The parameter object must define a value property');
}
```

Although necessary, this change isn't enough. During my tests, I noticed that dbstmt in idb-connector can't actually handle a null parameter. 

```
Error: PE: Failed to bindParam()
    at statement.bindParam.catch (/home/GUENEY/code/obi/node_modules/idb-pconnector/lib/dbPool.js:262:20)
Caused By:
 Error: SQLBindParmeter FAILED
SQLSTATE=HY009 SQLCODE=-99999 Fehler bei SQL Call Level Interface aufgetreten.
    at stmt.bindParam (/home/GUENEY/code/obi/node_modules/idb-pconnector/lib/statement.js:31:18)
```

This means that parameter arrays such as: 

```JS
[ 'Clementina DuBuque',
  'Moriah.Stanton',
  'Rey.Padberg@karina.biz',
  'Kattie Turnpike',
  'Suite 198',
  'Lebsackbury',
  '31428-2261',
  '-38.2386',
  '57.2232',
  '024-648-3804',
  null ]
```
also don't work and throw the same error as above.

**Comment by abmusse** [comment]
@KerimG 

Thanks for pointing this out.

I ran into the same `SQLSTATE=HY009 SQLCODE=-99999` error when bind parameters as null using `idb-connector`.

I think we should also open this issue on [idb-connector](https://github.com/IBM/nodejs-idb-connector/issues) repository.

**Comment by abmusse** [comment]
https://github.com/IBM/nodejs-idb-connector/issues/75

**Comment by abmusse** [comment]
@KerimG 

A new version of [idb-connector](https://www.npmjs.com/package/idb-connector) has been released with patches to allow binding a `null`.

**Comment by KerimG** [comment]
@abmusse 

Great stuff. Thank you! I will test it out ASAP. I think we can close the issue for now.
