### ISSUE TITLE
Prepare Execute Parameter Array

### ISSUE THREAD

**Issue by M0rwhsky** [IBM/nodejs-idb-pconnector#48]
When working with:
_pool.prepareExecute(sql,params)_

I am receiving the following Error:

> Error: The parameter object must define a value property

 

I believe this is due to an issue inside of routine **setupParms()**

My code looks as follows:
`  const sql = `CALL <LIB>.<PROCEDURE> (?, ?, ?, ?, ?, ?, ?)`

  const params = [
    {value: 'PARM1', io: 'in', asClob: false},
    {value: 'PARM2', io: 'in', asClob: false},
    {value: 'PARM3', io: 'in', asClob: false},
    {value: 'PARM4', io: 'in', asClob: false},
    {value: 'PARM5', io: 'out', asClob: true},
    {value: 0, io: 'out', asClob: false},
    {value: 'PARM6', io: 'out', asClob: false}
  ];    

await pool.prepareExecute(sql, params);`

Looking at the IDB-pconnector Code I see this which I am thinking should be equal too null "not" not equal too null:

Line : **_if (!value && value !== null)_**

`   * Internal helper function to format params and set Param Indicator & Bind Type
   * @param {array} params - an array of values to bind. type of values should be:
   * (string , number , or null)
   * @param {object} options - an object with config options to set for all parameters.
   * Currently, the input/output indicator is the only available option to set:
   * {io: in | out | both}.
   * This will override the default which is to bind as 'both'.
   * @returns {array} - an array of bounded params properly formated to use.
   */
  setupParams(params, options) {
    const boundParams = [];
    let { io } = options;

    io = io || 'both';

    params.forEach((parameter) => {
      if (parameter instanceof Object) {
        const { value, asClob = false } = parameter;

        if (!value && value !== null) {
          throw new Error('The parameter object must define a value property');
        }`

Or there could be something wrong with my Code.  Any feedback would be appreciated.  Thank You... 
M0rwhsky

**Comment by abmusse** [comment]
Seems like any falsy value execpt for null will cause the error [here](https://github.com/IBM/nodejs-idb-pconnector/blob/master/lib/dbPool.js#L331) :

`Error: The parameter object must define a value property`

This param:
```js
{value: 0, io: 'out', asClob: false},
```

The value 0 here which is falsy caused the condition to be true and throw the error.

You can see this issue in the [repl](https://repl.it/repls/TrivialSuspiciousDebugging)

As a fix I think the condition cause the error when `value` is undefined because `0`, `boolean`, and `null` would all be valid values here.

Should be patched to:

```
if (typeof value === 'undefined') {
  throw new Error('The parameter object must define a value property');
}

```

**Comment by M0rwhsky** [comment]
Thank you @abmusse I wasn't thinking of null acutally being a valid value but your are absolutely correct.  Much better patch.

**Comment by abmusse** [comment]
@M0rwhsky 

1.0.8 has been published to NPM. This includes a bug fix for this issue.
