### ISSUE TITLE
Program connects and when there is sql error, it leaves the jobs hanging out there

### ISSUE THREAD

**Issue by jordiwes** [IBM/nodejs-idb-pconnector#56]
We have a client which has many QSQSRVR jobs when there is a program encountering an SQL error...

Connection:
```
const {
  DBPool, Statement, SQL_ATTR_DBC_SYS_NAMING, SQL_TRUE
} = require('idb-pconnector');

this.pool = new DBPool({
      url: '*LOCAL'
    }, {incrementSize: 1});
    this.connection = this.pool.attach();
  },
```
Sql executed via:
```
 statement = new Statement(conn.connection);
    await statement.prepare(sqlStatement);
    await statement.execute();
```

SQL gets error in job:
Value for column or variable too long.
Job is in CNDW status.

When program reconnects, new job is spawned. The client ends up having many many jobs.
1) Why are jobs not reused?
2) Is there a way we can prevent this?

![hr2](https://user-images.githubusercontent.com/3420429/72109083-ee007e80-32e9-11ea-80fc-1a0b8016e91e.png)

![hr1](https://user-images.githubusercontent.com/3420429/72109093-f22c9c00-32e9-11ea-9a16-d2e134cd42a6.png)

**Comment by abmusse** [comment]
Hello from your code snippet I do not see any calls to to `pool.detach(connection)`. This should be called when you are done with your query. This will close out the statement and make the connection available in the pool again. Without doing this the connection will not be available for reuse and the will create a new connection (new job) instead. 

Alternatively you could use  [DBPool.prepareExecute(sql)](https://github.com/IBM/nodejs-idb-pconnector/tree/master/docs#dbpoolrunsqlsql) which handles this for you.

**Comment by 2upmedia** [comment]
@abmusse that did the job. Thanks! We had it there, but if a statement threw an exception the detach was never called. So we got that fixed.

**Comment by kadler** [comment]
Sounds like the problem was resolved. Is there anything else to do here or can this issue be closed?

**Comment by jordiwes** [comment]
Thanks all
