### ISSUE TITLE
npm not updated to 1.1 still on 1.0.8

### ISSUE THREAD

**Issue by larsandersson-ifpi** [IBM/nodejs-idb-pconnector#81]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by abmusse** [comment]
Hello @larsandersson-ifpi One #76 lands I think we should be good to release 1.1.0.

**Comment by kadler** [comment]
@larsandersson-ifpi We would appreciate it if you filled out the issue template instead of just leaving the placeholder questions.
