### ISSUE TITLE
Ryver Signup Link is Expired

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-idb-pconnector#82]
I tried to click on our signup badge but the link is expired.

![image](https://user-images.githubusercontent.com/33973272/75932018-fed9f600-5e3b-11ea-838b-7102eba94ae8.png)

@ThePrez 

Is it possible to setup signup link that does not expire?

This article might be useful

https://support.ryver.com/generate-a-signup-url/

**Comment by kadler** [comment]
@NattyNarwhal you're an admin there, right? Can you regenerate the link?

**Comment by NattyNarwhal** [comment]
Does https://ibmioss.ryver.com/application/signup/members/9tJsXDG7_iSSi1Q work for you?

**Comment by abmusse** [comment]
> Does https://ibmioss.ryver.com/application/signup/members/9tJsXDG7_iSSi1Q work for you?

No, that also shows `This sign-up link is no longer valid.`

**Comment by NattyNarwhal** [comment]
Weird, it's giving me the option to create an account. Let me see what I can generate.

**Comment by NattyNarwhal** [comment]
I just checked the admin console; that's the only current signup link and it claims its active...
![Screenshot from 2020-03-04 19-40-50](https://user-images.githubusercontent.com/3161292/75933332-19b66580-5e50-11ea-8a23-2522b57774da.png)

**Comment by kadler** [comment]
@abmusse if you are already logged in it will give you that error message

**Comment by abmusse** [comment]
Ok, this issue might be on my end.

Opening the link in a different browser or incognito tab it shows the signup form.

![image](https://user-images.githubusercontent.com/33973272/75933548-dd7b0900-5e3f-11ea-9f49-220866319c2a.png)

@NattyNarwhal 

Will this link expire sometime?

**Comment by NattyNarwhal** [comment]
It hasn't expired for years. Bizarrely, it also offered to let me sign up without being in an incognito window; I suspect both are problematic on Ryver's part.

**Comment by abmusse** [comment]
> It hasn't expired for years. Bizarrely, it also offered to let me sign up without being in an incognito window; I suspect both are problematic on Ryver's part.

Yeah it was strange message should just redirect us to the forum or tell the user you are already signed up.

Thanks for confirming its still active!
