### ISSUE TITLE
Add package-lock.json

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-idb-pconnector#85]
We should commit our [package-lock.json](https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md#package-lockjson5----a-manifestation-of-the-manifest) for various reasons:

- Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.

- Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.

- To facilitate greater visibility of tree changes through readable source control diffs.

- And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

**Comment by kadler** [comment]
Agreed as npm recommends this as well.
