### ISSUE TITLE
DBPool 'new connection' event emitter issues

### ISSUE THREAD

**Issue by abmusse** [IBM/nodejs-idb-pconnector#87]
**Please complete the following information:**
- Node.js version: v12.16.2
- idb-connector version: 1.2.8
- idb-pconnector version: 1.1.0 (latest master)
- IBM i version: 7.2

**Describe the bug**

Performing library list setup within the `'new connection'` event handler has a synchronization issue.
 
**To Reproduce**

```js
const { DBPool } = require('idb-pconnector');

async function setLibListExample() {
  const pool = new DBPool({ url: '*LOCAL' }, { incrementSize: 3, debug: true });

  pool.on('new connection', async (connection) => {
    await connection.setLibraryList(['QIWS', 'QXMLSERV']);
  });

  pool.attach();

  const results = await pool.runSql('SELECT * FROM QCUSTCDT');
 console.log(`results:\n ${JSON.stringify(results)}`);
}

setLibListExample().catch((error) => {
  throw error;
  console.error(error);
});
```
**Output**
```
Initializing the pool
Creating Connection 0...
SetConnAttr() attr = 10004, value = 1, rc = 0
Connection 0 created
Creating Connection 1...
SetConnAttr() attr = 10004, value = 1, rc = 0
Connection 1 created
Creating Connection 2...
SetConnAttr() attr = 10004, value = 1, rc = 0
Connection 2 created
Finding available Connection...
Connection 1 found
Executing SQL...
SQL Statement: SELECT * FROM QCUSTCDT
SQLExecDirect(-1): SELECT * FROM QCUSTCDT
SQLExecDirect(0): CALL QSYS2.QCMDEXC('CHGLIBL LIBL(QIWS QXMLSERV)')
SQLNUMRESULTSCOLS(0) Column Count = 0
Detaching Connection 1...
SQLFreeStmt: stmth 5 [SQL_DROP]
SQLFreeStmt(0)
Connection 1 detached
Error: runSql: Failed to exec()
    at ../node_modules/idb-pconnector/lib/dbPool.js:219:18
    at async DBPool.runSql (../node_modules/idb-pconnector/lib/dbPool.js:217:17)
    at async setLibListExample (../event-test.js:12:19)
Caused By:
 Error: SQLSTATE=42704 SQLCODE=-204 QCUSTCDT in *LIBL type *FILE not found.
    at Object.<anonymous> (../node_modules/idb-pconnector/lib/statement.js:135:18)
NO RESULTS: SQLExecDirect() callSQLFreeStmt: stmth 12 [SQL_DROP]
SQLFreeStmt(0)
SQLExecDirect(0): CALL QSYS2.QCMDEXC('CHGLIBL LIBL(QIWS QXMLSERV)')
SQLNUMRESULTSCOLS(0) Column Count = 0
NO RESULTS: SQLExecDirect() callSQLFreeStmt: stmth 11 [SQL_DROP]
SQLFreeStmt(0)
SQLExecDirect(0): CALL QSYS2.QCMDEXC('CHGLIBL LIBL(QIWS QXMLSERV)')
SQLNUMRESULTSCOLS(0) Column Count = 0
NO RESULTS: SQLExecDirect() callSQLFreeStmt: stmth 10 [SQL_DROP]
SQLFreeStmt(0)
```

As you can see from the output above setting up the library list occurs after the query. The library list is not setup yet therefore the library containing `QCUSCDT` (QIWS) was not found.

**Additional context**

One solution to get this working properly is to have a user provided function that gets called each time a new connection is created. Like what was proposed in https://github.com/IBM/nodejs-idb-pconnector/issues/46#issuecomment-511555115. I would suggest that this be an async function so that we can `await` the function. Doing this would require `attach` to return a promise though. That would be a breaking change requiring a new major version.

For now I think its best we revert 6d9c1935173f3792a6dc7b7ccd92d6c14f813f0b.

Then add milestones for v2.0.0 to make `attach` return a promise. That way can implement a solution like https://github.com/IBM/nodejs-idb-pconnector/issues/46#issuecomment-511555115.

**Comment by kadler** [comment]
So it seems that the emitted events can happen "out of order" with pool.attach(), leading to a race condition.

It seems you are right that we need to use a callback instead so that we can ensure that the function is called before prior to the connection joining the pool.
