### ISSUE TITLE
DBPool.prepareExecute should provide a way to enable numeric type conversion

### ISSUE THREAD

**Issue by patrickhrastnik** [IBM/nodejs-idb-pconnector#96]
**Is your feature request related to a problem? Please describe.**
A colleague of mine and I are currently investigating idb-pconnector for sql queries. 
We came across an issue: All result values are transported as strings. Thus, if you convert a result set to JSON (e.g. as a response on a web request), the numeric values aren't represented as numerics in the JSON string.
After further research I came across recent changes: `Statement.enableNumericTypeConversion` provides a way to auto-convert the result values to their numeric expression.
Currently we implemented `DBPool.prepareExecute`, but to use this feature we have to basically use the internal code of this function in our own implementation, so we can set the numeric flag.
So I suggest to add a way to set this property without access to a Statement instance.

**Describe the solution you'd like**
Maybe you could add a property to the `options` object for the function?
Or what I think would be even better: Maybe there's a way to set this flag globally (because in our runtime we want every sql statement to behave this way), e.g. `DBPool.enableNumericTypeConversion` or something like that.

**Comment by abmusse** [comment]
Hello :wave: @patrickhrastnik I think your later suggestion to have `DBPool.enableNumericTypeConversion` makes sense.

We could have a `enableNumericTypeConversion` boolean instance variable to the DBPool class. Within [prepareExecute](https://github.com/IBM/nodejs-idb-pconnector/blob/master/lib/dbPool.js#L243) we can check if this is set and enable it on the Statement.

**Comment by patrickhrastnik** [comment]
Thanks for the quick response @abmusse! 
If you don't mind I'd like to give it a try and to provide some possible implementation.

**Comment by ThePrez** [comment]
Go away, stalebot!

**Comment by patrickhrastnik** [comment]
Haha thanks @ThePrez 😄
It's gonna take some time til I can get around my Pull Request. I didn't want to release untested code, that's why it's still a Draft. Unfortunately I can't test it right now, due to some tasks with higher business priority.
I'll come back asap, I promise!

**Comment by patrickhrastnik** [comment]
Update on the changes: I was able to test them now, and they seem to work fine.
