### ISSUE TITLE
fetchAll keys lower case

### ISSUE THREAD

**Issue by larsandersson-ifpi** [IBM/nodejs-idb-pconnector#98]
when I use the idb-pconnector. and fetch result, i would like getting the key in lower case.

Is there a parameter to set to choose case of the keys. Now all keys is returned as upper case

**Comment by jhonnattan123** [comment]
I understand that it returns them according to how you created the column, if you created it without using quotes, it will always be uppercase

**Comment by abmusse** [comment]
Right, You can solve this creating the table with lower case fields using quotes as @jhonnattan123 mentioned. 

```sql
CREATE TABLE TEST.Persons (
    PersonID int, -- will be stored as uppercase
    "LastName" varchar(255), -- will save case
    "firstname" varchar(255) -- will save case
)

INSERT INTO TEST.Persons VALUES(1, 'Doe', 'John')

SELECT * FROM TEST.Persons

```
![image](https://user-images.githubusercontent.com/33973272/97200300-0a897c80-177f-11eb-82f8-bb96af63d174.png)


Or You can use Th SQL `AS` keyword to return the fields as you desire:

```sql
SELECT PERSONID AS "personID" FROM TEST.Persons
```

![image](https://user-images.githubusercontent.com/33973272/97203715-3575cf80-1783-11eb-9926-029c5773eab1.png)


Or from JS you can create a wrapper function that iterates over the result set and converts the key to lower case.
